set nocompatible  
set autoindent
set cindent 
set smartindent 
set number
set shiftwidth=4    
set showmatch      
set smartcase     
set ruler          
set cursorline     
set hlsearch      
set tabstop=4      
set background=dark
syntax on         
